export const CONTACT_DETAILS_DIALOG = 'CONTACT_DETAILS_DIALOG';
export const ADD_CONTACT_DIALOG = 'ADD_CONTACT_DIALOG';
export const EDIT_CONTACT_DIALOG = 'EDIT_CONTACT_DIALOG';
export const DELETE_CONTACT_DIALOG = 'DELETE_CONTACT_DIALOG';
export const DELETE_SELECTED_CONTACTS_DIALOG = 'DELETE_SELECTED_CONTACTS_DIALOG';
export const COVER_PRINT_AREA_DIALOG = 'COVER_PRINT_AREA_DIALOG';