export const GET_ALL_CONTACTS_SUCCESS = 'GET_ALL_CONTACTS_SUCCESS';
export const GET_ALL_CONTACTS_LOADING = 'GET_ALL_CONTACTS_LOADING';
export const GET_ALL_CONTACTS_FAILURE = 'GET_ALL_CONTACTS_FAILURE';

export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_LOADING = 'CREATE_CONTACT_LOADING';
export const CREATE_CONTACT_FAILURE = 'CREATE_CONTACT_FAILURE';

export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_LOADING = 'UPDATE_CONTACT_LOADING';
export const UPDATE_CONTACT_FAILURE = 'UPDATE_CONTACT_FAILURE';

export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_LOADING = 'DELETE_CONTACT_LOADING';
export const DELETE_CONTACT_FAILURE = 'DELETE_CONTACT_FAILURE';
