/* CONTACTS */

export const GET_ALL_CONTACTS_SUCCESS = 'GET_ALL_CONTACTS_SUCCESS';
export const GET_ALL_CONTACTS_LOADING = 'GET_ALL_CONTACTS_LOADING';
export const GET_ALL_CONTACTS_FAILURE = 'GET_ALL_CONTACTS_FAILURE';

export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_LOADING = 'CREATE_CONTACT_LOADING';
export const CREATE_CONTACT_FAILURE = 'CREATE_CONTACT_FAILURE';

export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_LOADING = 'UPDATE_CONTACT_LOADING';
export const UPDATE_CONTACT_FAILURE = 'UPDATE_CONTACT_FAILURE';

export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_LOADING = 'DELETE_CONTACT_LOADING';
export const DELETE_CONTACT_FAILURE = 'DELETE_CONTACT_FAILURE';

export const SELECT_ALL_CONTACTS = 'SELECT_ALL_CONTACTS';
export const DESELECT_ALL_CONTACTS = 'DESELECT_ALL_CONTACTS';
export const SELECT_CONTACT = 'SELECT_CONTACT';
export const DESELECT_CONTACT = 'DESELECT_CONTACT';

export const SET_CURRENT_CONTACT = 'SET_CURRENT_CONTACT';
export const CHANGE_CURRENT_CONTACT_PROFILE_PIC = 'CHANGE_CURRENT_CONTACT_PROFILE_PIC';

export const SORT_CONTACTS = 'SORT_CONTACTS';
export const FILTER_CONTACTS = 'FILTER_CONTACTS';

export const TOGGLE_CONTACTS_VIEW = 'TOGGLE_CONTACTS_VIEW';

/* DISTANCE */

export const SET_COVER_PRINT_AREA_DISTANCE = 'SET_COVER_PRINT_AREA_DISTANCE';

export const GET_DISTANCE = 'GET_DISTANCE';
export const GET_DISTANCE_SUCCESS = 'GET_DISTANCE_SUCCESS';
export const GET_DISTANCE_LOADING = 'GET_DISTANCE_LOADING';
export const GET_DISTANCE_FAILURE = 'GET_DISTANCE_FAILURE';

export const UPDATE_DISTANCE = 'UPDATE_DISTANCE';
export const UPDATE_DISTANCE_SUCCESS = 'UPDATE_DISTANCE_SUCCESS';
export const UPDATE_DISTANCE_LOADING = 'UPDATE_DISTANCE_LOADING';
export const UPDATE_DISTANCE_FAILURE = 'UPDATE_DISTANCE_FAILURE';

/* DIALOGS */

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
